version: '3.6'

services:
  counties-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=webapidemo
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webapidemo_net.pfx
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=counties;User=sa;Password=seq1erverTw3nyyTwo;TrustServerCertificate=True;Encrypt=false
      - ENABLE_CORS=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./https:/https/:ro
    networks:
      - localdev